[package]
name = "EP-GTK"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

mysql = "21.0.2"
glib = "0.14.8"
gio = "0.14.8"
pango = "0.14.8"
gtk = "0.14.3"

